// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReelView.Infrastructure.Data;

#nullable disable

namespace ReelView.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122154127_AdicionarFavoritos")]
    partial class AdicionarFavoritos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ReelView.Core.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MidiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MidiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("ReelView.Core.Models.Midia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Midias");

                    b.HasDiscriminator<string>("Tipo").HasValue("Midia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ReelView.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ReelView.Core.Models.UsuarioFavorito", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MidiaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId", "MidiaId");

                    b.HasIndex("MidiaId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("ReelView.Core.Models.Filme", b =>
                {
                    b.HasBaseType("ReelView.Core.Models.Midia");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Filme");
                });

            modelBuilder.Entity("ReelView.Core.Models.Serie", b =>
                {
                    b.HasBaseType("ReelView.Core.Models.Midia");

                    b.Property<int>("Episodios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temporadas")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Serie");
                });

            modelBuilder.Entity("ReelView.Core.Models.Avaliacao", b =>
                {
                    b.HasOne("ReelView.Core.Models.Midia", "Midia")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReelView.Core.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReelView.Core.Models.UsuarioFavorito", b =>
                {
                    b.HasOne("ReelView.Core.Models.Midia", "Midia")
                        .WithMany()
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReelView.Core.Models.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReelView.Core.Models.Midia", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("ReelView.Core.Models.Usuario", b =>
                {
                    b.Navigation("Favoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
